image: docker:20.10.16

services:
  - docker:20.10.16-dind

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  AWS_S3_ACCESS_KEY_ID: $AWS_S3_ACCESS_KEY_ID
  AWS_S3_SECRET_ACCESS_KEY: $AWS_S3_SECRET_ACCESS_KEY
  AWS_STORAGE_BUCKET_NAME: $AWS_STORAGE_BUCKET_NAME

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE
    - echo "Compile complete."
